# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SidePaneSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SidePaneSample
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'ReachabilitySwift'
  pod 'JASidePanelsSwift'
  pod 'Font-Awesome-Swift'



  target 'SidePaneSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
